spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka.topic:
  user-random-topic: User-Random-Topic
  user-created-topic: User_created-Topic