management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      health:
        show-details: always

resilience4j:
  #  retry:
  #    instances:
  #      inventoryRetry:
  #        maxRetryAttempts: 3
  #        waitDuration: 1s

  ratelimiter:
    instances:
      inventoryRateLimiter:
        limitRefreshPeriod: 1s
        limitForPeriod: 300
        timeOutDuration: 10ms

  circuitbreaker:
    instances:
      inventoryCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10