spring:
  application:
    name: config-server



server:
  port: 8888

#eureka config
eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true